version: '3.8'

services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - '3001:3001'

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
